import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useCallback } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const isIFrame = (input: HTMLElement | null): input is HTMLIFrameElement =>
    input !== null && input.tagName === "IFRAME";

  const postCrossDomainMessage = useCallback((msg: unknown) => {
    var win = document.getElementById("ifr");

    console.log("antes do if");
    if (isIFrame(win) && win.contentWindow) {
      win.contentWindow.postMessage(msg, window.location.href);
      console.log("dentro do if");
    }
    console.log("dps do if");
  }, []);

  useEffect(() => {
    var postMsg = { login: "user from website1" }; // this is just example
    postCrossDomainMessage(postMsg);
  }, [postCrossDomainMessage]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>this is the: domain 1</h1>
        <button onClick={() => postCrossDomainMessage("opa, foi pelo botao")}>
          post cross domain
        </button>
        <iframe
          style={{ width: "300px", height: "300px" }}
          src="https://info-cross-domain-2.vercel.app/getlocalstorage.html"
          id="ifr"
        ></iframe>
      </main>
    </>
  );
}
